export * from './authenticationController.service';
import { AuthenticationControllerService } from './authenticationController.service';
export * from './cacheController.service';
import { CacheControllerService } from './cacheController.service';
export * from './fileController.service';
import { FileControllerService } from './fileController.service';
export * from './filmCollectionController.service';
import { FilmCollectionControllerService } from './filmCollectionController.service';
export * from './filmCommentController.service';
import { FilmCommentControllerService } from './filmCommentController.service';
export * from './filmController.service';
import { FilmControllerService } from './filmController.service';
export * from './filmDubbingController.service';
import { FilmDubbingControllerService } from './filmDubbingController.service';
export * from './filmEpisodeController.service';
import { FilmEpisodeControllerService } from './filmEpisodeController.service';
export * from './filmRatingController.service';
import { FilmRatingControllerService } from './filmRatingController.service';
export * from './filmRecommendationsController.service';
import { FilmRecommendationsControllerService } from './filmRecommendationsController.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export * from './watchRoomController.service';
import { WatchRoomControllerService } from './watchRoomController.service';
export const APIS = [AuthenticationControllerService, CacheControllerService, FileControllerService, FilmCollectionControllerService, FilmCommentControllerService, FilmControllerService, FilmDubbingControllerService, FilmEpisodeControllerService, FilmRatingControllerService, FilmRecommendationsControllerService, UserControllerService, WatchRoomControllerService];
