export * from './authenticationController.service';
import { AuthenticationControllerService } from './authenticationController.service';
export * from './cacheController.service';
import { CacheControllerService } from './cacheController.service';
export * from './filmCollectionController.service';
import { FilmCollectionControllerService } from './filmCollectionController.service';
export * from './filmCommentController.service';
import { FilmCommentControllerService } from './filmCommentController.service';
export * from './filmController.service';
import { FilmControllerService } from './filmController.service';
export * from './filmDubbingController.service';
import { FilmDubbingControllerService } from './filmDubbingController.service';
export * from './filmEpisodeController.service';
import { FilmEpisodeControllerService } from './filmEpisodeController.service';
export * from './filmInfoLookupController.service';
import { FilmInfoLookupControllerService } from './filmInfoLookupController.service';
export * from './filmRatingController.service';
import { FilmRatingControllerService } from './filmRatingController.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export const APIS = [AuthenticationControllerService, CacheControllerService, FilmCollectionControllerService, FilmCommentControllerService, FilmControllerService, FilmDubbingControllerService, FilmEpisodeControllerService, FilmInfoLookupControllerService, FilmRatingControllerService, UserControllerService];
