/**
 * Rezflix Backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FilmRatingDto } from './filmRatingDto';
import { ShortUserDto } from './shortUserDto';


export interface CommentDto { 
    text: string;
    filmId: number;
    id: number;
    createdAt: string;
    author: ShortUserDto;
    authorRating?: FilmRatingDto;
}

