/**
 * Rezflix Backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommentDto } from './commentDto';


export interface CommentListDto { 
    total: number;
    items: Array<CommentDto>;
}

