/**
 * Rezflix Backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EpisodeDto } from './episodeDto';


export interface EpisodeListDto { 
    total: number;
    items: Array<EpisodeDto>;
}

