/**
 * Rezflix Backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EpisodeStatusDto } from './episodeStatusDto';


export interface EpisodeCriteriaDto { 
    page?: number;
    size?: number;
    orderBy?: string;
    isDescendingOrder?: boolean;
    minWatchOrder?: number;
    maxWatchOrder?: number;
    query?: string;
    status?: EpisodeStatusDto;
}



