/**
 * Rezflix Backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum FileTypeDto {

    USER_AVATAR = 'USER_AVATAR',

    FILM_POSTER = 'FILM_POSTER'
}

