/**
 * Rezflix Backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShortFilmCollectionDto } from './shortFilmCollectionDto';


export interface FilmCollectionListDto { 
    total: number;
    items: Array<ShortFilmCollectionDto>;
}

