/**
 * Rezflix Backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FilmCriteriaDto { 
    page?: number;
    size?: number;
    orderBy?: string;
    isDescendingOrder?: boolean;
    query?: string;
}

