/**
 * Rezflix Backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShortUserDto } from './shortUserDto';
import { FilmDto } from './filmDto';


export interface FilmCollectionDto { 
    name: string;
    description?: string;
    id: number;
    films: Array<FilmDto>;
    owner: ShortUserDto;
}

