/**
 * Rezflix Backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FilmDto } from './filmDto';


export interface FilmListDto { 
    total: number;
    items: Array<FilmDto>;
}

