/**
 * Rezflix Backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FilmRatingDto } from './filmRatingDto';


export interface FilmDto { 
    title: string;
    description: string;
    id: number;
    totalRating: number;
    currentUserRating?: FilmRatingDto;
}

