/**
 * Rezflix Backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShortUserDto } from './shortUserDto';


export interface ShortFilmCollectionDto { 
    name: string;
    description?: string;
    id: number;
    owner: ShortUserDto;
}

