/**
 * Rezflix Backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserTypeDto } from './userTypeDto';


export interface UserCriteriaDto { 
    page?: number;
    size?: number;
    orderBy?: string;
    isDescendingOrder?: boolean;
    type?: UserTypeDto;
    query?: string;
}



